### PR TITLE
Change target

### PR DESCRIPTION
**Pull request by domfournier**

### CODE REVIEW

**Review by sebhmg — APPROVED** [review]

**Review by sebhmg — CHANGES_REQUESTED** [review]
now failure is
```
>           assert mesh.n_cells == 10586
E           assert 15136 == 10586
```

**Comment by domfournier** [comment]
> now failure is
> 
> ```
> >           assert mesh.n_cells == 10586
> E           assert 15136 == 10586
> ```

What the heck is going on... reverting

**Comment by domfournier** [comment]
Don't know what to tell you, this PR doesn't do anything

**Comment by sebhmg** [comment]
> What the heck is going on... reverting

Test passes here but fails when using geoh5py 0.9.0-rc in https://github.com/MiraGeoscience/plate-simulation/pull/19

**Pull request closed without merging**
